language: python
python:
- '3.6'
install:
- pip install -r test-requirements.txt
- pip install tox-travis
script:
- printenv | grep SPOTIPY
- printenv | grep DISCORD
- tox
env:
  global:
    - SPOTIPY_CLIENT_ID=6685f1fa024b4580b165fd845b74e8e4
    - SPOTIPY_CLIENT_SECRET=02c2f1a11ef141898921ba58949bf41c
    - SPOTIPY_REDIRECT_URI=https://www.google.com/
    - DISCORD_TOKEN=NTE3MzY1NTcwMjg3Njk3OTIy.DuBKKQ.Ge6SrYlpjfxv7s7vRdjiyYC3TRI
