language: python
python:
- '3.6'
install:
- pip install -r test-requirements.txt
- pip install tox-travis
script:
- tox -e analysis
- tox -e py36-test
before_install:
- openssl aes-256-cbc -K $encrypted_c65d6799360d_key -iv $encrypted_c65d6799360d_iv
  -in creds.json.enc -out creds.json -d
after_success:
- codecov
env:
  global:
    secure: YqCbsvl9X031FEv+5OpxusYGDhwQuuF4kBQExBzsoRE9CQEMCwoNlJddut2/V0J9wZJOYq41bTEQmjeBBoZompBSS02yvM95Mvdl0Zc07VyvadghrFD3TEZRqzRy/euW71O4OWmxx5LTpueNnfVmB6I2y+CtnyBoBw2hqcjqczQwM2gF6UfHof3Z4p/WMLomI5xisivewyrLncYTHcGoWE3M88VTFV1d+T+SxWWOgV1L3ZXG9ymGTqKN+qoJXrfc1A37WMXiAgxqntuX0IowzJ8NxQ+txFANYsiZknLnkkj9Sp1o9bW4PKjqknvpWLsw8MtNRZ86mevJiCtGdcaQIcjvNRJ6ZLLndtz0n4D0rs0FmJh2aIJObhfvS4ki/RjzBumFRzEpxgb+blopDLf7ukmqm7DaOwQsyOCHbv19Igxx1Pt7UGHHNQGZuhMWu6e34IgpAonQN0z/Y5WBQ4dPG6ytQvI6G2K6YabA75ypaU4JWSzU4PXSKLrLwK5wc0fx2mlUOGrBMpfRzZBBYqSXtKXKDvYySxqpoGyOiX1x44PaVUmafCQTW8/vnF0P7LqQ8mCAn7NsphG0XK97LxIMtd/e+eJF7RoIia1D8GB1nmDh0aUlA3hdXX/Zs6FU0krIKehj1ra0vOxeGFSEqOxAVXpHAAswI3p20fH/1LpfU98=
